[package]
name = "rahim"
version = "0.1.0"
edition = "2021"

[dependencies]
firebase-auth-sdk = "0.1.0"
actix-web = "4"
serde = "1.0.204"
dotenv = "0.15.0"
futures = "0.3  "

[dependencies.mongodb]
version = "2.2.0"